name: Build Arch ISO with ArchInstall Commit

on:
  push:
    branches:
      - master
      - main # In case i adopt this convention in the future
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mikuxdev/archlinux-archiso:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Import SSH key
        run: |
          cd /home/builder
          sudo -u builder bash -c '
          mkdir -p /tmp/work /home/builder/out
          '
      - run: ls -la /home/builder
      - run: pwd
      - run: find .
      - name: builds
        run: |
          cd /home/builder
          sudo -u builder bash -c '
          pacman --noconfirm -S archiso mkinitcpio-archiso
          git clone https://github.com/MikuX-Dev/custom-archiso.git
          sudo mkarchiso -v -w /tmp/work/ -o /home/builder/out/ ./custom-archiso/profile
          '
      - uses: actions/upload-artifact@v3
        with:
          name: ArchFiery ISO
          path: /home/builder/out/*.iso